# Generated by Django 4.1.2 on 2022-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nserie', models.CharField(max_length=100)),
                ('NomProducto', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Cantidad', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
            ],
        ),
    ]
