# Generated by Django 4.1.2 on 2022-12-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_boleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='usuario1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.boleta'),
            preserve_default=False,
        ),
    ]
