# Generated by Django 4.1.3 on 2022-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_boleta_usuario1_productos_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
